name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.3.1

      - name: Install dependencies
        run: poetry install --with test

      - name: Run ruff
        run: poetry run ruff check .

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Start infrastructure
        run: docker compose -f compose.test.yaml --env-file test.env up -d test-postgres test-redis test-minio

      - name: Run tests
        run: |
          set -a
          source test.env
          poetry run pytest
          set +a

      - name: Down infrastructure
        if: always()
        run: docker compose -f compose.test.yaml down
